name: macos-dockerhub-hithesis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Install docker
      # Set actions-setup-docker version to 1.0.8. See https://github.com/dapr/cli/issues/965
      uses: docker-practice/actions-setup-docker@1.0.8
    - uses: actions/checkout@v1
    - name: Pull docker image
      run: |
        docker pull syvshc/hithesis

    - name: Test doc
      run: |
        docker run --rm -i -v $(pwd):/home/thesis syvshc/hithesis make doc
    - name: Test chinese thesis
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitbook/chinese
        docker run --rm -i -v $(pwd):/home/thesis syvshc/hithesis make thesis
        cd $CURRENTDIR
    - name: Test english thesis
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitbook/english
        docker run --rm -i -v $(pwd):/home/thesis syvshc/hithesis make thesis
        cd $CURRENTDIR
    - name: Test reports
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitart/reports
        docker run --rm -i -v $(pwd):/home/thesis syvshc/hithesis make report
        cd $CURRENTDIR
    - name: Test reportplus
      run: |
        CURRENTDIR=$(pwd)
        cd examples/hitart/reportplus
        docker run --rm -i -v $(pwd):/home/thesis syvshc/hithesis make report
        cd $CURRENTDIR
